#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba32f) uniform readonly image2D PrecomputedData;
layout(set = 0, binding = 1, rgba32f) uniform image2D Buffer0;
layout(set = 0, binding = 2, rgba32f) uniform image2D Buffer1;

layout(push_constant) uniform PushConstants {
    uint size;
    uint stage;
} params;

vec2 ComplexMult(vec2 a, vec2 b) {
	return vec2(a.r * b.r - a.g * b.g, a.r * b.g + a.g * b.r);
}

void main() {
    uvec3 id = gl_GlobalInvocationID;
    if (id.x >= params.size || id.y >= params.size)
        return;
    
    vec4 data = imageLoad(PrecomputedData, ivec2(params.stage, id.y));
    uvec2 inputsIndices = uvec2(data.ba);
    
    vec4 buffer_x = imageLoad(Buffer0, ivec2(id.x, inputsIndices.x));
    vec4 buffer_y = imageLoad(Buffer0, ivec2(id.x, inputsIndices.y));
    vec2 result = buffer_x.rg + ComplexMult(vec2(data.r, -data.g), buffer_y.rg);
    imageStore(Buffer1, ivec2(id.xy), vec4(result, 0.0, 0.0));
}